### PR TITLE
ZenFocus should be Zen Focus

### PR DESCRIPTION
**Pull request by ehguo**

### CODE REVIEW

**Comment by chengsieuly** [comment]
actually, it's the other way around! =) We're making it `ZenFocus` instead of `Zen Focus`

**Comment by ehguo** [comment]
lol so ZenFocus everywhere?

**Comment by chengsieuly** [comment]
yea, `ZenFocus` wherever possible

**Comment by ehguo** [comment]
Okay I found 2 locations, lemme know if you can think of any other ones

**Pull request merged**
