### PR TITLE
Add ability to choose sound for each phase

### PR DESCRIPTION
**Pull request by chengsieuly**
capture

### CODE REVIEW

**Comment by chengsieuly** [comment]
@ehguo hmm, i personally feel it's too much on the ui to have more checkboxes. i feel that if user wants to disable tick, they would want to disable ticks for all phases. however, on a later enhancement, we can add a 'None' option which would play no sound for that phase.

**Comment by ehguo** [comment]
Well I was thinking if you are on break there's no point in having a tick, so maybe just tick during focus.

**Comment by ehguo** [comment]
@chengsieuly Or maybe instead of a checkbox, just have a 'None' option in the drop down.

**Comment by chengsieuly** [comment]
@ehguo yea, I think that would be best. We can add that on a future enhancement when we add more sounds

**Pull request merged**
